name: progressbar11_launcher
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0
  shared_preferences: ^2.0.6

flutter:
  uses-material-design: true
